ALTER TABLE audit_task_current_state
  ADD COLUMN IF NOT EXISTS engineer_tier TEXT,
  ADD COLUMN IF NOT EXISTS engineer_tier_rationale TEXT,
  ADD COLUMN IF NOT EXISTS architect_handoff_version INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ready_for_engineering BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS implementation_commit_sha TEXT,
  ADD COLUMN IF NOT EXISTS implementation_pr_url TEXT,
  ADD COLUMN IF NOT EXISTS implementation_primary_reference JSONB,
  ADD COLUMN IF NOT EXISTS implementation_submission_version INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lock_owner TEXT,
  ADD COLUMN IF NOT EXISTS lock_acquired_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS lock_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS lock_reason TEXT,
  ADD COLUMN IF NOT EXISTS lock_action TEXT,
  ADD COLUMN IF NOT EXISTS latest_qa_outcome TEXT,
  ADD COLUMN IF NOT EXISTS latest_qa_run_id TEXT,
  ADD COLUMN IF NOT EXISTS latest_qa_actor_id TEXT,
  ADD COLUMN IF NOT EXISTS latest_qa_retest_scope JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS latest_qa_submission_version INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS latest_qa_routed_stage TEXT;
