'use strict';

const LANGGRAPH_SCHEMA = 'langgraph_checkpoint';
const GRAPH_VERSION = 'factory-v1';
const STATE_SCHEMA_VERSION = 1;
const DEFAULT_NAMESPACE = 'factory';
const DEFAULT_MAX_STATE_BYTES = 256 * 1024;
const DEFAULT_RETENTION_DAYS = 30;
const DEFAULT_OPERATION_TIMEOUT_MS = 10_000;
const DEFAULT_RESUME_LEASE_MS = 60_000;
const DEFAULT_POOL_BUDGET = 2;

module.exports = Object.freeze({
  DEFAULT_MAX_STATE_BYTES,
  DEFAULT_NAMESPACE,
  DEFAULT_OPERATION_TIMEOUT_MS,
  DEFAULT_POOL_BUDGET,
  DEFAULT_RESUME_LEASE_MS,
  DEFAULT_RETENTION_DAYS,
  GRAPH_VERSION,
  LANGGRAPH_SCHEMA,
  STATE_SCHEMA_VERSION,
});
