#!/usr/bin/env node
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const ALLOWLIST_PATH = path.join('config', 'lint-source-allowlist.json');
const CODE_EXTENSIONS = new Set(['.cjs', '.js', '.jsx', '.mjs', '.ts', '.tsx']);
const INCLUDE_ROOTS = new Set(['api', 'lib', 'scripts', 'src', 'tests']);
const EXCLUDED_SEGMENTS = new Set([
  '.artifacts',
  '.next',
  '.tmp',
  '.vercel',
  'build',
  'coverage',
  'dist',
  'generated',
  'node_modules',
  'playwright-report',
  'third_party',
  'vendor',
]);
const ALLOWLISTABLE_RULES = new Set([
  'readability:bundled-source',
  'readability:generated-source',
  'readability:minified-source',
]);
const GENERATED_PATTERN = /\b(@generated|auto-generated|autogenerated|generated by|do not edit|do not modify)\b/i;
const BUNDLED_INDICATORS = [
  '__webpack' + '_require__',
  'webpack' + 'Bootstrap',
  'sourceMapping' + 'URL=',
  'rollup ' + 'generated',
  'vite ' + 'modulepreload',
];
const PLACEHOLDER_PATTERN = /^(tbd|todo|n\/a|none|unknown)$/i;
const MAX_MINIFIED_LINE_LENGTH = 1000;
const DENSE_FILE_LENGTH = 2000;

function normalizePath(filePath) {
  return filePath.split(path.sep).join('/').replace(/^\.\//, '');
}

function isSafeRelativePath(filePath) {
  if (!filePath || path.isAbsolute(filePath)) return false;
  return !normalizePath(filePath).split('/').includes('..');
}

function isIncludedPath(filePath) {
  const normalized = normalizePath(filePath);
  const segments = normalized.split('/');
  const extension = path.extname(normalized);
  return CODE_EXTENSIONS.has(extension)
    && INCLUDE_ROOTS.has(segments[0])
    && !segments.some((segment) => EXCLUDED_SEGMENTS.has(segment));
}

function isRegularExistingFile(root, filePath) {
  const absolute = path.join(root, filePath);
  return fs.existsSync(absolute) && fs.statSync(absolute).isFile();
}

function gitDiscoveredFiles(root) {
  const output = execFileSync(
    'git',
    ['ls-files', '--cached', '--others', '--exclude-standard'],
    { cwd: root, encoding: 'utf8' },
  );
  return output.trim().split('\n').filter(Boolean);
}

function discoverLintFiles(options = {}) {
  const root = options.root || ROOT;
  const discovered = options.files || gitDiscoveredFiles(root);
  return [...new Set(discovered.map(normalizePath))]
    .filter((filePath) => isIncludedPath(filePath))
    .filter((filePath) => isRegularExistingFile(root, filePath))
    .sort();
}

function finding(pathName, line, rule, message) {
  return { path: pathName, line, rule, message };
}

function formatFinding(item) {
  return `${item.path}:${item.line} ${item.rule} ${item.message}`;
}

function redactionSafeRemediation() {
  return 'commit readable source, move generated output under an excluded path, or add allowlist metadata with owner, reason, and followUp';
}

function readSource(root, filePath) {
  const buffer = fs.readFileSync(path.join(root, filePath));
  if (buffer.includes(0)) return { binary: true, text: '' };
  return { binary: false, text: buffer.toString('utf8') };
}

function lineFindings(filePath, text) {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const results = [];
  lines.forEach((line, index) => {
    if (/[ \t]+$/.test(line)) {
      results.push(finding(filePath, index + 1, 'lint:trailing-whitespace', 'trailing whitespace'));
    }
    if (line.includes('\t')) {
      results.push(finding(filePath, index + 1, 'lint:tab-character', 'tab character'));
    }
  });
  return results;
}

function firstMatchingLine(lines, pattern) {
  const index = lines.findIndex((line) => pattern.test(line));
  return index === -1 ? null : index + 1;
}

function bundledLine(lines) {
  const index = lines.findIndex((line) => {
    const normalized = line.toLowerCase();
    return BUNDLED_INDICATORS.some((indicator) => normalized.includes(indicator.toLowerCase()));
  });
  return index === -1 ? null : index + 1;
}

function minifiedLine(text) {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const nonEmpty = lines.filter((line) => line.trim());
  const longLine = lines.findIndex((line) => line.length > MAX_MINIFIED_LINE_LENGTH);
  if (longLine !== -1) return longLine + 1;
  if (text.length > DENSE_FILE_LENGTH && nonEmpty.length <= 3) return 1;
  return null;
}

function readabilityFindings(filePath, text) {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const results = [];
  const generatedLine = firstMatchingLine(lines.slice(0, 25), GENERATED_PATTERN);
  const bundledLineNumber = bundledLine(lines);
  const compactLine = /\.min\.[cm]?js$/.test(filePath) ? 1 : minifiedLine(text);
  if (generatedLine) {
    results.push(finding(filePath, generatedLine, 'readability:generated-source', `authored source appears generated; ${redactionSafeRemediation()}`));
  }
  if (bundledLineNumber) {
    results.push(finding(filePath, bundledLineNumber, 'readability:bundled-source', `authored source appears bundled; ${redactionSafeRemediation()}`));
  }
  if (compactLine) {
    results.push(finding(filePath, compactLine, 'readability:minified-source', `authored source appears minified; ${redactionSafeRemediation()}`));
  }
  return results;
}

function scanFile(root, filePath) {
  const source = readSource(root, filePath);
  if (source.binary) return { skippedBinary: true, findings: [] };
  return {
    skippedBinary: false,
    findings: [
      ...lineFindings(filePath, source.text),
      ...readabilityFindings(filePath, source.text),
    ],
  };
}

function loadAllowlist(root) {
  const absolutePath = path.join(root, ALLOWLIST_PATH);
  if (!fs.existsSync(absolutePath)) return { version: 1, entries: [] };
  return JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
}

function validateString(value, label, entry, errors) {
  if (typeof value !== 'string' || !value.trim() || PLACEHOLDER_PATTERN.test(value.trim())) {
    errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', `entry for ${entry.path || '<missing path>'} must include ${label}`));
  }
}

function validateAllowlist(payload, scannedFiles) {
  const errors = [];
  if (!payload || payload.version !== 1 || !Array.isArray(payload.entries)) {
    return {
      entries: [],
      errors: [finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-schema', 'allowlist must be JSON with version 1 and an entries array')],
    };
  }

  const scanned = new Set(scannedFiles);
  const seen = new Set();
  const entries = [];
  for (const entry of payload.entries) {
    for (const cleanEntry of expandAllowlistEntry(entry, errors)) {
      validateAllowlistEntry(cleanEntry, scanned, seen, errors);
      if (isSafeRelativePath(cleanEntry.path)) entries.push(cleanEntry);
    }
  }
  return { entries, errors };
}

function expandAllowlistEntry(entry, errors) {
  const paths = Array.isArray(entry.paths) ? entry.paths : [entry.path];
  const rules = Array.isArray(entry.rules) ? entry.rules : [];
  if (!paths.length || paths.some((entryPath) => typeof entryPath !== 'string')) {
    errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', 'entry must include path or paths'));
    return [];
  }
  return paths.map((entryPath) => ({
    ...entry,
    path: normalizePath(entryPath || ''),
    paths: undefined,
    rules,
  }));
}

function validateAllowlistEntry(entry, scanned, seen, errors) {
  if (!isSafeRelativePath(entry.path)) {
    errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', 'entry path must be a safe relative path'));
  } else if (!scanned.has(entry.path)) {
    errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:stale-entry', `entry for ${entry.path} does not match a scanned authored source file`));
  }
  if (!entry.rules.length) {
    errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', `entry for ${entry.path || '<missing path>'} must include at least one rule`));
  }
  for (const rule of entry.rules) {
    if (!ALLOWLISTABLE_RULES.has(rule)) {
      errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', `entry for ${entry.path || '<missing path>'} has unsupported rule ${rule}`));
    }
    const key = `${entry.path}|${rule}`;
    if (seen.has(key)) {
      errors.push(finding(ALLOWLIST_PATH, 1, 'allowlist:invalid-entry', `duplicate entry for ${entry.path} ${rule}`));
    }
    seen.add(key);
  }
  validateString(entry.owner, 'owner', entry, errors);
  validateString(entry.reason, 'reason', entry, errors);
  validateString(entry.followUp, 'followUp', entry, errors);
}

function allowlistKeys(entries) {
  const keys = new Set();
  for (const entry of entries) {
    for (const rule of entry.rules) keys.add(`${entry.path}|${rule}`);
  }
  return keys;
}

function applyAllowlist(findings, entries) {
  const keys = allowlistKeys(entries);
  const active = [];
  const suppressed = [];
  for (const item of findings) {
    const key = `${item.path}|${item.rule}`;
    if (ALLOWLISTABLE_RULES.has(item.rule) && keys.has(key)) {
      suppressed.push(item);
    } else {
      active.push(item);
    }
  }
  return { active, suppressed };
}

function staleAllowlistFindings(entries, findings) {
  const current = new Set(findings.map((item) => `${item.path}|${item.rule}`));
  const stale = [];
  for (const entry of entries) {
    for (const rule of entry.rules) {
      if (!current.has(`${entry.path}|${rule}`)) {
        stale.push(finding(ALLOWLIST_PATH, 1, 'allowlist:stale-entry', `entry for ${entry.path} ${rule} no longer matches an active readability finding`));
      }
    }
  }
  return stale;
}

function durationSeconds(start) {
  return Number(process.hrtime.bigint() - start) / 1e9;
}

function runLint(options = {}) {
  const root = options.root || ROOT;
  const start = process.hrtime.bigint();
  const files = discoverLintFiles({ root, files: options.files });
  const payload = options.allowlist || loadAllowlist(root);
  const allowlist = validateAllowlist(payload, files);
  const scanResults = files.map((filePath) => scanFile(root, filePath));
  const scannedCount = scanResults.filter((result) => !result.skippedBinary).length;
  const skippedBinary = scanResults.filter((result) => result.skippedBinary).length;
  const scanFindings = scanResults.flatMap((result) => result.findings);
  const staleFindings = staleAllowlistFindings(allowlist.entries, scanFindings);
  const { active, suppressed } = applyAllowlist(scanFindings, allowlist.entries);
  const failures = [...allowlist.errors, ...staleFindings, ...active]
    .sort((left, right) => formatFinding(left).localeCompare(formatFinding(right)));
  return {
    duration: durationSeconds(start),
    failures,
    files,
    scannedCount,
    skippedBinary,
    suppressedCount: suppressed.length,
  };
}

function printResult(result, output = process) {
  const summary = `files scanned: ${result.scannedCount}, binary skipped: ${result.skippedBinary}, allowlisted readability findings: ${result.suppressedCount}, duration: ${result.duration.toFixed(3)}s`;
  if (result.failures.length) {
    output.stderr.write(`${result.failures.map(formatFinding).join('\n')}\n`);
    output.stderr.write(`lint checks failed: ${result.failures.length} findings (${summary})\n`);
    return 1;
  }
  output.stdout.write(`lint checks passed (${summary})\n`);
  return 0;
}

if (require.main === module) {
  process.exitCode = printResult(runLint());
}

module.exports = {
  ALLOWLIST_PATH,
  ALLOWLISTABLE_RULES,
  CODE_EXTENSIONS,
  EXCLUDED_SEGMENTS,
  INCLUDE_ROOTS,
  applyAllowlist,
  discoverLintFiles,
  formatFinding,
  isIncludedPath,
  lineFindings,
  minifiedLine,
  readabilityFindings,
  runLint,
  scanFile,
  staleAllowlistFindings,
  validateAllowlist,
};
