'use strict';

const GRAPHILE_WORKER_SCHEMA = 'graphile_worker';
const JOB_RUNTIME_SCHEMA = 'job_runtime';
const JOB_RUNTIME_CATALOG_VERSION = 1;
const JOB_PAYLOAD_MAX_BYTES = 64 * 1024;
const JOB_PAYLOAD_MAX_DEPTH = 8;
const JOB_PAYLOAD_MAX_ARRAY_LENGTH = 100;
const JOB_RUNTIME_DEFAULT_CONCURRENCY = 4;
const JOB_RUNTIME_DEFAULT_RESERVED_CONNECTIONS = 4;
const JOB_RUNTIME_DEFAULT_SHUTDOWN_MS = 30_000;
const JOB_RUNTIME_DEFAULT_RETENTION_DAYS = 30;
const JOB_RUNTIME_DEFAULT_RETENTION_INTERVAL_MS = 60 * 60 * 1_000;
const JOB_RUNTIME_DEFAULT_RETENTION_BATCH = 1_000;

const DELIVERY_STATUS = Object.freeze({
  PENDING: 'pending_enqueue',
  QUEUED: 'queued',
  RUNNING: 'running',
  RETRYING: 'redelivery_pending',
  ACKNOWLEDGED: 'delivery_acknowledged',
  FAILED: 'delivery_failed',
});

module.exports = {
  DELIVERY_STATUS,
  GRAPHILE_WORKER_SCHEMA,
  JOB_PAYLOAD_MAX_ARRAY_LENGTH,
  JOB_PAYLOAD_MAX_BYTES,
  JOB_PAYLOAD_MAX_DEPTH,
  JOB_RUNTIME_CATALOG_VERSION,
  JOB_RUNTIME_DEFAULT_CONCURRENCY,
  JOB_RUNTIME_DEFAULT_RESERVED_CONNECTIONS,
  JOB_RUNTIME_DEFAULT_RETENTION_BATCH,
  JOB_RUNTIME_DEFAULT_RETENTION_DAYS,
  JOB_RUNTIME_DEFAULT_RETENTION_INTERVAL_MS,
  JOB_RUNTIME_DEFAULT_SHUTDOWN_MS,
  JOB_RUNTIME_SCHEMA,
};
